spring:
  application:
    name: template

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.79.55:3306/testdb
    username: root
    password: testmysql
  data:
    redis:
      host: 117.72.79.55
      port: 6379
      database: 0
server:
  port: 8081


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


#logging:
#  level:
#    root: debug